accounts/urls.py
from django.urls import path
from .views import profile , profile_edit , signup, myreservation, mylisting


app_name = 'accounts'

urlpatterns = [
    path('signup',signup , name='signup'),
    path('profile/',profile,name='profile'),
    path('reservation/',myreservation,name='reservation'),
    path('mylisting/',mylisting,name='mylisting'),
    path('profile/edit', profile_edit , name='profile_edit')
]

blog/urls.py
from django.urls import path
from . import views
from .api_view import post_list_api, post_detail_api, post_search_api




app_name = 'blog'

urlpatterns = [ 
    path('', views.PostList.as_view(), name='post_list'),
    path('<slug:slug>', views.PostDetail.as_view(), name='post_detail'),
    
    path('category/<str:slug>', views. PostByCategory.as_view(), name='post_by_category'),
    path('tags/<slug:slug>', views.PostByTags.as_view(), name='post_by_tags'),
    
    ## API
    path('api/list', post_list_api, name='post_list_api'),
    path('api/list/<int:id>', post_detail_api, name='post_detail_api'),
    path('api/list/filter/<str:query>', post_search_api, name='post_detail_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/' , include('accounts.urls', namespace='accounts')),
    
    path('admin/', admin.site.urls),
    path('', include('settings.urls', namespace='home')),
    path('property/', include('property.urls', namespace='property')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace='about')),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user = models.ForeignKey(User, related_name='user_profile', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile/'  , blank=True, null=True)
    phone_number = models.CharField(max_length=16 , blank=True, null=True)
    address = models.CharField(max_length=50 , blank=True, null=True)


    def __str__(self):
        return str(self.user)

    
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from . models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image','phone_number','address']

accounts/views.py
from django.shortcuts import redirect, render
from .models import Profile
from .forms import UserForm , ProfileForm , UserCreateForm
from django.urls import reverse
from django.contrib.auth import authenticate, login
from property.models import PropertyBook, Property
# Create your views here.

def signup(request):
    if request.method == 'POST':
        signup_form = UserCreateForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            # return redirect(reverse('login'))
            username = signup_form.cleaned_data['username']
            password = signup_form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect(reverse('accounts:profile'))
    
    else:
        signup_form = UserCreateForm()

    return render(request,'registration/signup.html',{'signup_form':signup_form})



def profile(request):
    profile = Profile.objects.get(user = request.user)
    return render(request,'profile/profile.html',{'profile':profile})



def profile_edit(request):
    profile = Profile.objects.get(user = request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST , instance=request.user)
        profile_form = ProfileForm(request.POST , request.FILES , instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            my_form = profile_form.save(commit=False)
            my_form.user = request.user
            my_form.save()
            return redirect(reverse('accounts:profile'))
    
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance = profile)       

    return render(request,'profile/profile_edit.html',{
        'user_form' : user_form , 
        'profile_form' : profile_form
    })
    


def myreservation(request):
    property_list = PropertyBook.objects.filter(user=request.user)
    
    return render(request, 'profile/reservation.html', {'property_list':property_list})





def mylisting(request):
    property_list = Property.objects.filter(owner=request.user)
    
    return render(request, 'profile/mylisting.html', {'property_list':property_list})

accounts/templates/profile/mylisting.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block body %}

<!-- Map Section Begin -->
<div class="map">
    <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2942.5524090066037!2d-71.10245469994108!3d42.47980730490846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e3748250c43a43%3A0xe1b9879a5e9b6657!2sWinter%20Street%20Public%20Parking%20Lot!5e0!3m2!1sen!2sbd!4v1577299251173!5m2!1sen!2sbd"
        height="500" style="border: 0" allowfullscreen=""></iframe>
    <div class="icon-list">
        <div class="icon icon-1">1</div>
        <div class="icon icon-2">2</div>
        <div class="icon icon-3">3</div>
        <div class="icon icon-4">4</div>
        <div class="icon icon-5">5</div>
    </div>
</div>
<!-- Map Section End -->

<!-- Property Section Begin -->
<section class="property-section spad">
    <div class="container">
        <div class="row">

            <div class="col-lg-9">
                <h4 class="property-title">My Listing</h4>
                <div class="property-list">
                    {% for property in property_list %}

                    <div class="single-property-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="property-pic">
                                    <a href="{{property.get_absolute_url}}">
                                        <img src="{{ property.image.url }}" alt="image" />
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="property-text">
                                    <div class="s-text">For Sale</div>
                                    <h5 class="r-title">
                                        <a href="{{property.get_absolute_url}}">{{property.property.name}}</a>
                                    </h5>
                                    <div class="room-price">
                                        <span>Start From:</span>
                                        <h5>${{property.property.price}}</h5>
                                    </div>
                                    <div class="properties-location">
                                        <i class="icon_pin"></i> {{property.place}}
                                    </div>
                                    <p>{{property.description|safe|truncatewords:15}}</p>
                                    <ul class="room-features">
                                        <li>
                                            <i class="fa fa-arrows"></i>
                                            <p>5201 sqft</p>
                                        </li>
                                        <li>
                                            <i class="fa fa-bed"></i>
                                            <p>8 Bed Room</p>
                                        </li>
                                        <li>
                                            <i class="fa fa-bath"></i>
                                            <p>7 Baths Bed</p>
                                        </li>
                                        <li>
                                            <i class="fa fa-car"></i>
                                            <p>1 Garage</p>
                                        </li>
                                    </ul>

                                    <p class="bottom-area d-flex">
                                        <span class="ml-auto"><a href="{{property.get_absolute_url}}">View Villa</a></span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>


            </div>


        </div>
    </div>
</section>
<!-- Property Section End -->


{% endblock body %}

accounts/templates/profile/profile.html
{% extends 'base.html' %}
{% block body %}
{% load bootstrap5 %}
{% load static %}
<!-- Hero Section Begin -->
<section class="hero-section">
    <div class="hero-items owl-carousel">
        <div class="single-hero-item set-bg" data-setbg="{% static 'img/hero/hero-1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 offset-lg-2">
                        <div class="hero-text">
                            <h2>Profile</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- Hero Section End -->

<div class="container">
    <div class="row mt-5">
        <div class="col-md-6 mx-auto">
            {{profile.user.username}}

            {{profile.user.email}}
            
            
            {{profile.phone_number}}
            
            {{profile.address}}
            
            
            
            <h5><a href="{% url 'accounts:profile_edit' %}">Edit Profile</a></h5>
            <h5><a href="{% url 'accounts:reservation' %}">My Reservations</a></h5>
            <h5><a href="{% url 'accounts:mylisting' %}">My Listing</a></h5>
        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/profile/profile_edit.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% block body %}


<!-- Hero Section Begin -->
<section class="hero-section">
    <div class="hero-items owl-carousel">
        <div class="single-hero-item set-bg" data-setbg="{% static 'img/hero/hero-1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 offset-lg-2">
                        <div class="hero-text">
                            <h2>Edit Profile</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- Hero Section End -->

<div class="container">
    <div class="row mt-5">
        <div class="col-md-6 mx-auto">
            <h3>Edit Profile</h3>
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form user_form %}
                {% bootstrap_form profile_form %}
                {% buttons %}
                <button type="submit" class="btn btn-primary">Edit Profile</button>
                {% endbuttons %}
            </form>

        </div>
    </div>
</div>
{% endblock body %}

accounts/templates/profile/reservation.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block body %}

<!-- Map Section Begin -->
<div class="map">
    <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2942.5524090066037!2d-71.10245469994108!3d42.47980730490846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e3748250c43a43%3A0xe1b9879a5e9b6657!2sWinter%20Street%20Public%20Parking%20Lot!5e0!3m2!1sen!2sbd!4v1577299251173!5m2!1sen!2sbd"
        height="500" style="border: 0" allowfullscreen=""></iframe>
    <div class="icon-list">
        <div class="icon icon-1">1</div>
        <div class="icon icon-2">2</div>
        <div class="icon icon-3">3</div>
        <div class="icon icon-4">4</div>
        <div class="icon icon-5">5</div>
    </div>
</div>
<!-- Map Section End -->

<!-- Property Section Begin -->
<section class="property-section spad">
    <div class="container">
        <div class="row">

            <div class="col-lg-9">
                <h4 class="property-title">My reservation</h4>
                <div class="property-list">
                    {% for property in property_list %}

                    <div class="single-property-item">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="property-pic">
                                    <a href="{{property.property.get_absolute_url}}">
                                        <img src="{{ property.property.image.url }}" alt="image" />
                                    </a>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="property-text">
                                    <div class="s-text">For Sale</div>
                                    <h5 class="r-title">
                                        <a href="{{property.get_absolute_url}}">{{property.property.name}}</a>
                                    </h5>
                                    <div class="room-price">
                                        <span>Start From:</span>
                                        <h5>${{property.property.price}}</h5>
                                    </div>
                                    <div class="properties-location">
                                        <i class="icon_pin"></i> {{property.property.place}}
                                    </div>
                                    <p>{{property.property.description|safe|truncatewords:15}}</p>
                                    <ul class="room-features">
                                        <li>
                                            <i class="fa fa-arrows"></i>
                                            <p>5201 sqft</p>
                                        </li>
                                        <li>
                                            <i class="fa fa-bed"></i>
                                            <p>8 Bed Room</p>
                                        </li>
                                        <li>
                                            <i class="fa fa-bath"></i>
                                            <p>7 Baths Bed</p>
                                        </li>
                                        <li>
                                            <i class="fa fa-car"></i>
                                            <p>1 Garage</p>
                                        </li>
                                    </ul>

                                    <p class="bottom-area d-flex">
                                        <span class="ml-auto"><a href="{{property.get_absolute_url}}">Add
                                                Review</a></span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                </div>


                <!-- pagination        -->


            </div>


        </div>
    </div>
</section>
<!-- Property Section End -->


{% endblock body %}