blog/urls.py
from django.urls import path
from . import views
from .api_view import post_list_api, post_detail_api, post_search_api




app_name = 'blog'

urlpatterns = [ 
    path('', views.PostList.as_view(), name='post_list'),
    path('<slug:slug>', views.PostDetail.as_view(), name='post_detail'),
    
    path('category/<str:slug>', views. PostByCategory.as_view(), name='post_by_category'),
    path('tags/<slug:slug>', views.PostByTags.as_view(), name='post_by_tags'),
    
    ## API
    path('api/list', post_list_api, name='post_list_api'),
    path('api/list/<int:id>', post_detail_api, name='post_detail_api'),
    path('api/list/filter/<str:query>', post_search_api, name='post_detail_api'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/' , include('accounts.urls', namespace='accounts')),
    
    path('admin/', admin.site.urls),
    path('', include('settings.urls', namespace='home')),
    path('property/', include('property.urls', namespace='property')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace='about')),
    path('summernote/', include('django_summernote.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(User, related_name='post_author', on_delete=models.CASCADE, verbose_name=_("author"))
    title = models.CharField(max_length=100, verbose_name=_('title'))
    tags = TaggableManager()
    image = models.ImageField(_("image"),upload_to='post/')
    created_at = models.DateTimeField(_("created at"), default=timezone.now)
    description = models.TextField(_("description"),max_length=15000)
    category = models.ForeignKey('Category', related_name='post_category', on_delete=models.CASCADE, verbose_name=_("category"))
    slug = models.SlugField(_("url"), null=True, blank=True)
   
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)    
    
    def __str__(self):
        return self.title  
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name  

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post, Category
from taggit.models import Tag
from django.db.models import Q, Count

# Create your views here.


class PostList(ListView):
    model = Post
    paginate_by = 0
    
    def get_queryset(self):
        name = self.request.GET.get('q', '')
        object_list = Post.objects.filter(
            Q(title__icontains=name) |
            Q(description__icontains=name)
        )
        return object_list
    
    
    
class PostDetail(DetailView):
    model = Post
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all().annotate(post_count=Count('post_category'))
        context["tags"] = Tag.objects.all()
        context["recent_posts"] = Post.objects.all()[:2]
        return context
    
    

class PostByCategory(ListView):
    model = Post
    
    def get_queryset(self):
        object_list = Post.objects.filter(
            Q(category__name__icontains=self.kwargs['slug'])
        )
        return object_list
    


class PostByTags(ListView):
    model = Post
    
    
    def get_queryset(self):
        object_list = Post.objects.filter(
            Q(tags__name__icontains=self.kwargs['slug'])
        )
        return object_list
    
    
    

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% load static %}
{% block body %}


<!-- Blog Details Hero Section Begin -->
<section class="blog-details-hero set-bg" data-setbg="{% static 'img/blog/blog-details-hero.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="bd-hero-text">
                    <span>Real Estate</span>
                    <h2>{{post}}</h2>
                    <ul>
                        <li><i class="fa fa-user"></i> {{post.author}}</li>
                        <li><i class="fa fa-clock-o"></i> {{post.created_at|date:'F j Y'}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!--  Blog Details Hero Section Begin -->

<!-- Blog Details Section Begin -->
<section class="blog-details-section">

    <div class="container">
        <div class="row">
            <div class="sidebar-box">
                <form action="{% url 'blog:post_list' %}" method="GET" class="search-form">
                  <div class="form-group">
                    <span class="icon fa fa-search"></span>
                    <input type="text" name="q" class="form-control" placeholder="Type a keyword and hit enter">
                  </div>
                </form>
              </div>

            <div class="col-lg-10 text-center">
                <div class="blog-details-title">

                    <p>{{post.description}}</p>

                </div>
            </div>
            <div class="best-agents">
                <h4>Categories</h4>
                <a href="#" class="ba-item">


                    {% for category in categories %}

                    <a href="#" class="ba-item">
                        <li><a href="{% url 'blog:post_by_category' category %}">{{category}} <span>{{category.post_count}}</span></a></li>
    

                        {% endfor %}

          

              
            </div>

        </div>

        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="blog-details-pic">
                    <div class="bd-pic-item small-item set-bg" data-setbg="{% static 'img/blog/blog-details-1.jpg' %}">
                    </div>
                    <div class="bd-pic-item small-item set-bg" data-setbg="{% static 'img/blog/blog-details-2.jpg' %}">
                    </div>
                    <div class="bd-pic-item large-item set-bg" data-setbg="{% static 'img/blog/blog-details-3.jpg' %}">
                    </div>
                    <div class="bd-pic-item wide-item set-bg" data-setbg="{% static 'img/blog/blog-details-4.jpg' %}">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 offset-lg-2">

                <div class="tag-share-option">
                    <div class="tags">


                        {% for tag in post.tags.all %}
                        <a href="">{{tag}}</a>
                        {% endfor %}

  


                    </div>
                    <div class="social-share">
                        <span>Tags</span>

                        {% for tag in tags %}
                        <span><a href="{% url 'blog:post_by_tags' tag %}">{{tag}}</a></span>

                        {% endfor %}



                    </div>

                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="comment-option">
                    <h4> Comments</h4>

                    <div id="disqus_thread"></div>

                </div>
            </div>
        </div>



        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>You May Also Like</h2>
                </div>
            </div>


            {% for post in recent_posts %}
            <div class="col-lg-6">
                <div class="single-blog-item">
                    <div class="sb-pic">
                        <a href="{{post.get_absolute_url}}"> <img src="{{post.image.url}}" alt=""></a>

                    </div>
                    <div class="sb-text">
                        <ul>
                            <li><i class="fa fa-user"></i>{{post.author}}</li>
                            <li><i class="fa fa-clock-o"></i> {{post.created_at|date:'F j Y'}}</li>
                        </ul>
                        <h4><a href="{{post.get_absolute_url}}">{{post.title}}</a></h4>
                    </div>
                </div>
            </div>
            {% endfor %}



        </div>
    </div>
</section>
<!-- Blog Details Section End -->

<!-- Partner Carousel Section Begin -->
<div class="partner-section">
    <div class="container">
        <div class="partner-carousel owl-carousel">
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-1.png' %}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-2.png' %}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-3.png' %}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-4.png' %}" alt="">
                </div>
            </a>
            <a href="#" class="partner-logo">
                <div class="partner-logo-tablecell">
                    <img src="{% static 'img/partner/partner-5.png' %}" alt="">
                </div>
            </a>
        </div>
    </div>
</div>
<!-- Partner Carousel Section End -->


<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */

    var disqus_config = function () {
    this.page.url = "https://127.0.0.1:8000/{{post.get_absolute_url}}";  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = "{{post.slug}}"; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://tdj-luxury.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

{% endblock body %}

blog/templates/blog/post_list.html
{% extends 'base.html' %} 

{% load static %}
 {% block body %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Blog List</h2>
                        <div class="breadcrumb-option">
                            <a href="#"><i class="fa fa-home"></i> Home</a>
                            <span>Blog Default</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section Begin -->

    <!-- Blog Section Begin -->
    <section class="blog-section blog-page spad">
        <div class="container">
            <div class="row">


                
                {% for post in object_list %}
 
                <div class="col-lg-4 col-md-6">
                    <div class="single-blog-item">
                        <div class="sb-pic">
                       <a href="{{post.get_absolute_url}}"><img src="{{post.image.url}}" alt=""></a>     
                        </div>
                        <div class="sb-text">
                            <ul>
                                <li><i class="fa fa-user"></i> {{post.author}}</li>
                                <li><i class="fa fa-clock-o"></i> {{post.created_at|date:'F j Y'}}</li>
  
                            </ul>
                            <h4><a href="{{post.get_absolute_url}}">{{post}}</a></h4>
                        </div>
                    </div>
                </div>

                {% endfor %}
                    
                <div class="col-lg-12">
        <!-- pagination        -->

        {% if is_paginated %}
        <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <div class="property-pagination">
                {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}">&lt;</a>
                {% else %}
                <span class="disibled"></span>

                {% endif %} 
                {% for i in paginator.page_range %} 
                {% if page_obj.number == i %}
                <a href="#" class="active">{{i}}</a>
                {% else %}
                <a href="?page={{i}}">{{i}}</a>
                {% endif %} {% endfor %} {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">&gt;</a>
                {% else %}
                <span class="disibled"></span>

                {% endif %}
              </div>
            </div>
          </div>
        </div>
        {% endif %}
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Section End -->

    <!-- Partner Carousel Section Begin -->
    <div class="partner-section">
        <div class="container">
            <div class="partner-carousel owl-carousel">
                <a href="#" class="partner-logo">
                    <div class="partner-logo-tablecell">
                        <img src="{% static 'img/partner/partner-1.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="partner-logo">
                    <div class="partner-logo-tablecell">
                        <img src="{% static 'img/partner/partner-2.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="partner-logo">
                    <div class="partner-logo-tablecell">
                        <img src="{% static 'img/partner/partner-3.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="partner-logo">
                    <div class="partner-logo-tablecell">
                        <img src="{% static 'img/partner/partner-4.png' %}" alt="">
                    </div>
                </a>
                <a href="#" class="partner-logo">
                    <div class="partner-logo-tablecell">
                        <img src="{% static 'img/partner/partner-5.png' %}" alt="">
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- Partner Carousel Section End -->


    {% endblock body %}